<a href="https://colab.research.google.com/github/DaviFerreira0106/notebooks-inteligenciaArtificial/blob/main/Cria%C3%A7%C3%A3oArrayNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Criação de array e calculos matematicos, utilizando **`Numpy`**

## Importação da biblioteca

In [1]:
import numpy as np

## Criação da array

In [2]:
array = np.array([1, 2, 3, 4, 5])

## operações matemáticas básicas

In [3]:
array_soma = array + 10
array_mult = array * 2
array_sub = array - 5
array_div = array / 2

print(f"A soma é: {array_soma}")
print(f"A multiplicação é: {array_mult}")
print(f"A subtração é: {array_sub}")
print(f"A divisão é: {array_div}")

A soma é: [11 12 13 14 15]
A multiplicação é: [ 2  4  6  8 10]
A subtração é: [-4 -3 -2 -1  0]
A divisão é: [0.5 1.  1.5 2.  2.5]


## Criando **`array 2D`** (ou matriz 2x2, ou ainda matriz Bidimensional)


In [5]:
matriz = np.array([[1, 2, 4, 6], [3, 4, 8, 7]])

print(f"Matriz: \n{matriz}")

Matriz: 
[[1 2 4 6]
 [3 4 8 7]]


## Oprações matemáticas básicas com a matriz

In [6]:
matriz_soma = matriz + 5
matriz_sub = matriz - 6
matriz_mult = matriz * 2
matriz_div = matriz / 3

print(f"A soma é: \n{matriz_soma}")
print(f"A subtração é: \n{matriz_sub}")
print(f"A multiplicação é: \n{matriz_mult}")
print(f"A divisão é: \n{matriz_div}")

A soma é: 
[[ 6  7  9 11]
 [ 8  9 13 12]]
A subtração é: 
[[-5 -4 -2  0]
 [-3 -2  2  1]]
A multiplicação é: 
[[ 2  4  8 12]
 [ 6  8 16 14]]
A divisão é: 
[[0.33333333 0.66666667 1.33333333 2.        ]
 [1.         1.33333333 2.66666667 2.33333333]]
