<a href="https://colab.research.google.com/github/DaviFerreira0106/notebooks-inteligenciaArtificial/blob/main/Exercicio_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import numpy as np

print("\t\t\t EXERCÍCIOS NUMPY")

#Exercício1
array = np.linspace(start=1, stop=100, num=50, dtype=int)
print("\n\n Matriz com números inteiros de 1 à 100: ")
print(array)

#Exercício2
array_matriz = np.random.randint(17, size=(4,4))
fatiamento = array_matriz[0:3,:]
print("\n Matriz 4x4 com números inteiros de 1 à 16: ")
print(array_matriz)
print(f"\n Matriz 4x4 com números inteiros de 1 à 16 sem ultima linha: ")
print(fatiamento)

#Exercício3
array_zeros = np.zeros(15)
array_zeros[5] = 1
array_zeros[6] = 1
array_zeros[7] = 1
array_zeros[8] = 1
array_zeros[9] = 1
array_zeros[10] = 1
print("\n Array de 15 elemnetos que entre o 5º e 10º o valor é 1: ")
print(array_zeros)

#Exercício4
array_aleatorio = np.random.randint(100, size=101)
mediana = np.median(array_aleatorio)
print("\n Array de 100 números aleatórios")
print(array_aleatorio)
print(f"\n Mediana do array: {mediana}")

#Exercício5








			 EXERCÍCIOS NUMPY


 Matriz com números inteiros de 1 à 100: 
[  1   3   5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35
  37  39  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71
  73  75  77  79  81  83  85  87  89  91  93  95  97 100]

 Matriz 4x4 com números inteiros de 1 à 16: 
[[ 9 15 10 12]
 [ 9 11 13  6]
 [ 2  7  3  2]
 [ 5 14  2 14]]

 Matriz 4x4 com números inteiros de 1 à 16 sem ultima linha: 
[[ 9 15 10 12]
 [ 9 11 13  6]
 [ 2  7  3  2]]

 Array de 15 elemnetos que entre o 5º e 10º o valor é 1: 
[0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0.]

 Array de 100 números aleatórios
[79 93 13 90 27 64 72 26  9 47 61 51 82 35 44  8 58 73 74 95 57 91 15 92
 49 61 55 83 55 26 95 52 89 38 62 13  4 96 96 82 26 11 76 16 85 88 52 93
 34 60 30 29 43 59 24 59 53 85 96 26 23 93 73 80 12 95 31 48 17 49 26 89
 86 52 73 85 25 90 44 98 52 14 89 99 55 12 73 51 35 77 98 62 77 38 26  5
 63 45 36 24 21]

 Mediana do array: 55.0

 Moda do array: [158 186  26 180  54 128