<a href="https://colab.research.google.com/github/DaviFerreira0106/notebooks-inteligenciaArtificial/blob/main/Exercicio_Scipy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercícios de SciPy


## 1. Calcule a integral da função f(x) = x² sin(x) no intervalo de 0 a π

In [ ]:
from scipy import integrate
import numpy as np

def f(x):
  return x**2

resultado, erro = integrate.quad(f,0,np.pi)

print("Resultado: ", resultado)
print("Erro: ", erro)

Resultado:  10.335425560099939
Erro:  1.1474627426122306e-13


## 2. Resolva a equação diferencial **`dy/dx = x − y, com y(0) = 1`**, no intervalo de 0 a 10.

In [ ]:
from scipy.integrate import solve_ivp
import numpy as np

def equacao_diferencial(x, y):
  return x - y

resultado = solve_ivp(equacao_diferencial, [0, 10], [1], t_eval=np.linspace(0, 10, 100))

print(f"Resultado: {resultado}")

Resultado:   message: The solver successfully reached the end of the integration interval.
  success: True
   status: 0
        t: [ 0.000e+00  1.010e-01 ...  9.899e+00  1.000e+01]
        y: [[ 1.000e+00  9.089e-01 ...  8.899e+00  9.000e+00]]
      sol: None
 t_events: None
 y_events: None
     nfev: 50
     njev: 0
      nlu: 0


## 3. Encontre as raízes da função **`f(x) = X*X*X*X - 3x³ + 2`** utilizando SciPy.

In [ ]:
from scipy.optimize import root

def f(x):
  return x**4 - 3*x**3 + 2

resultado = root(f, 0)

print(f"Resultado: {resultado.x}")


Resultado: [0.]


## 4. Use a função de otimização de SciPy para maximizar f(x) = −x² + 4x + 1.

In [ ]:
from scipy.optimize import minimize

def f(x):
  return -x**2 + 4*x + 1

resultado = minimize(f, 0)

print(f"Resultado: {resultado.x}")

Resultado: [-1034.24]


## 5. Calcule a transformada de Fourier de um sinal composto de sin(2πt) e cos(4πt).

In [ ]:
from scipy.fft import fft
import numpy as np

t = np.linspace()

## 6. Encontre a matriz inversa de uma matriz 5x5 de números aleatórios.

In [1]:
from scipy.linalg import inv
import numpy as np

matriz = np.random.rand(5, 5)
matriz_inversa = inv(matriz)

print(f"Matriz: {matriz}")
print(f"Matriz inversa: {matriz_inversa}")


Matriz: [[0.90471855 0.33018307 0.91049074 0.40408531 0.40268997]
 [0.84932047 0.00804715 0.62835011 0.89351143 0.47225177]
 [0.19923203 0.51691072 0.43805229 0.29734076 0.52230423]
 [0.25663942 0.62605221 0.00948086 0.86463982 0.25548614]
 [0.71402226 0.42447688 0.50584762 0.02625155 0.00401803]]
Matriz inversa: [[-7.74099158  4.57924905  2.90249554 -2.28789837  5.77441869]
 [ 0.26863292 -1.0581098   0.33650353  0.83627533  0.52375627]
 [10.5334379  -5.51068513 -4.28294705  2.44136876 -6.47418209]
 [ 4.57340433 -2.03367153 -2.71677097  2.15806937 -3.39342741]
 [-8.75095702  5.07994524  5.61310625 -3.23104066  4.64068649]]


## 7. Use a função de interpolação cúbica de SciPy para interpolar os dados (0, 0),(1, 2),(2, 3),(3, 5),(4, 4)


In [2]:
from scipy import interpolate
import numpy as np

x = np.array([0, 1, 2, 3, 4])
y = np.array([0, 2, 3, 5, 4])

interpolacao = interpolate.interp1d(x, y, kind='cubic')

x_novos = np.linspace(0, 4, 100)
y_novos = interpolacao(x_novos)

print(f"Valores interpolados: {y_novos}")

Valores interpolados: [0.         0.14451353 0.28191173 0.41242545 0.53628555 0.65372289
 0.76496832 0.87025271 0.9698069  1.06386176 1.15264814 1.23639689
 1.31533888 1.38970496 1.45972599 1.52563282 1.58765631 1.64602732
 1.70097671 1.75273533 1.80153403 1.84760368 1.89117513 1.93247923
 1.97174685 2.00920885 2.04509606 2.07963937 2.11306961 2.14561766
 2.17751435 2.20899056 2.24027714 2.27160494 2.30320482 2.33530764
 2.36814425 2.40194552 2.43694229 2.47336543 2.51144578 2.55141422
 2.59350159 2.63793875 2.68495656 2.73478588 2.78765755 2.84380244
 2.90345141 2.96683531 3.03417263 3.10539741 3.18015924 3.25809536
 3.33884298 3.42203932 3.50732163 3.59432711 3.682693   3.77205652
 3.86205489 3.95232535 4.04250511 4.1322314  4.22114146 4.30887249
 4.39506173 4.4793464  4.56136373 4.64075094 4.71714526 4.79018392
 4.85950413 4.92474313 4.98553813 5.04152637 5.09234507 5.13763146
 5.17702275 5.21015618 5.23666897 5.25619835 5.26838153 5.27285576
 5.26925824 5.25722621 5.23639689 5.2064

## 8. Resolva o sistema de equações **`3x + 2y = 5 e x + 4y = 6`**


In [3]:
from scipy import linalg
import numpy as np

a = np.array([[3, 2], [1, 4]])
b = np.array([5, 6])

solucao = linalg.solve(a, b)

print(f"Solução: {solucao}")

Solução: [0.8 1.3]


## 9. Ajuste uma curva quadrática aos pontos (1, 2),(2, 4),(3, 5),(4, 7),(5, 8).


In [6]:
from scipy.optimize import curve_fit
import numpy as np

x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 5, 7, 8])

def parabola(x, a, b, c):
  return a*x**2 + b*x + c

parametros, _ = curve_fit(parabola, x, y)

print(f"Parâmetros da curva quadrática: {parametros}")


Parâmetros da curva quadrática: [-0.07142857  1.92857143  0.2       ]


## 10. Calcule a integral dupla da função **`f(x, y) = xy + x²`** no intervalo **`[0, 2]`** para **`x`** e **`[0, 1]`** para **`y`**

In [11]:
from scipy import integrate

def f(x, y):
  return x*y + x**2

resultado, erro = integrate.dblquad(f, 0, 2, lambda y: 0, lambda y: 1)
print(f"Resultado: {resultado}")

Resultado: 1.6666666666666665


## 11. Encontre os autovalores e autovetores de uma matriz 4x4 de números inteiros aleatórios.

In [13]:
from scipy import linalg
import numpy as np

matriz = np.random.randint(4, size=(4,4))
autovalores, autovetores = linalg.eig(matriz)

print(f"Matriz: {matriz}")
print(f"Autovalores: {autovalores}")
print(f"Autovetores: {autovetores}")


Matriz: [[0 0 1 0]
 [3 1 2 3]
 [0 1 0 3]
 [3 0 1 2]]
Autovalores: [ 4.11528007+0.j         -0.84320142+1.35714563j -0.84320142-1.35714563j
  0.57112276+0.j        ]
Autovetores: [[ 0.11463669+0.j          0.25476282+0.41004468j  0.25476282-0.41004468j
  -0.12057264+0.j        ]
 [ 0.78460452+0.j          0.13974224+0.00746213j  0.13974224-0.00746213j
  -0.94335239+0.j        ]
 [ 0.47176209+0.j         -0.77130672+0.j         -0.77130672-0.j
  -0.06886178+0.j        ]
 [ 0.38560953+0.j          0.17020823-0.35141256j  0.17020823+0.35141256j
   0.30134129+0.j        ]]


## 12.  Resolva a equação e**x − x² = 0 para encontrar a raiz mais próxima de x = 1


In [16]:
from scipy.optimize import root
import numpy as np

def f(x, e):
  return x**2 - e**x

resultado = root(f, 1, args=(1))

print(f"Resultado: {resultado.x}")


Resultado: [1.]


## 13.  Calcule o determinante de uma matriz 6x6 de números aleatórios entre -10 e 10


In [17]:
from scipy import linalg
import numpy as np

matriz = np.random.randint(-10, 11, size=(6, 6))
determinante = linalg.det(matriz)

print(f"Matriz: {matriz}")
print(f"Determinante: {determinante}")

Matriz: [[  7  -6   8   8   4  -7]
 [ -3  -8 -10   0  -5   2]
 [ -7   7   6   7   6 -10]
 [  8  -4  -8   4  -2  10]
 [ -3   3  -9  -8  -4   6]
 [ -2  -7  -5  -6  -2  -2]]
Determinante: -154856.0


## 14.  Utilize a função de otimização multivariada para minimizar **`f(x, y) = (x−2)² + (y − 3)²`**


In [22]:
from scipy.optimize import minimize


def f(x):
  return (x[0] - 2)**2 + (x[1] - 3)**2

resultado = minimize(f, [0, 0])

print(f"Resultado: {resultado.x}")

Resultado: [1.99999999 2.99999999]


## 15.  Calcule a transformada de Fourier inversa de um sinal complexo gerado aleatoriamente.


In [23]:
from scipy.fft import fft
import numpy as np

sinal = np.random.rand(100) + 0.5*np.random.rand(100)*1j
sinal_inverso = fft(sinal)

print(f"Sinal: {sinal}")
print(f"Sinal inverso: {sinal_inverso}")

Sinal: [0.63132619+0.41206566j 0.32475413+0.02204329j 0.36813796+0.0836128j
 0.85893669+0.42716404j 0.88273243+0.15727198j 0.13602624+0.21296772j
 0.25563309+0.13612892j 0.10005106+0.20442032j 0.47127098+0.04117811j
 0.43470214+0.20665785j 0.11922152+0.01684981j 0.88879157+0.02178228j
 0.04014291+0.2095954j  0.65947312+0.41385452j 0.83513404+0.16210438j
 0.87849384+0.06975658j 0.69884853+0.1864493j  0.83208829+0.24579477j
 0.12501595+0.18344696j 0.10077301+0.10359984j 0.7098967 +0.17051122j
 0.02262747+0.09510402j 0.08183087+0.14052952j 0.22528923+0.00800202j
 0.86165038+0.04475752j 0.58232366+0.29806646j 0.26742013+0.04745898j
 0.70785929+0.31602486j 0.04489176+0.1917578j  0.30446439+0.34228811j
 0.79913645+0.30303149j 0.18827576+0.24459898j 0.60620343+0.08112657j
 0.53241229+0.07990678j 0.7223849 +0.37391614j 0.92099934+0.19081216j
 0.22787425+0.25028539j 0.58819103+0.12040765j 0.85044531+0.38485859j
 0.54560415+0.14339651j 0.34533869+0.14945077j 0.64442507+0.28723622j
 0.88452834+0.

## 16. Resolva a equação diferencial de segunda ordem d²y/dx² +y = 0, com condições iniciais y(0) = 1 e y¹(0) = 0

In [24]:
from scipy.integrate import solve_ivp
import numpy as np

def equacao_diferencial(t, y):
  return y

resultado = solve_ivp(equacao_diferencial, [0, 10], [1, 0], method='RK45')

print(f"Resultado: {resultado.y}")


Resultado: [[1.00000000e+00 1.11315550e+00 3.14156385e+00 1.21790893e+01
  5.38987081e+01 2.53113766e+02 1.22170390e+03 5.97308326e+03
  2.19978158e+04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]]


## 17. Encontre a raiz cúbica de 27 utilizando SciPy


In [25]:
from scipy.optimize import root

def f(x):
  return x**3 - 27

resultado = root(f, 0)

print(f"Resultado: {resultado.x}")

Resultado: [0.0432]


## 18. Interpole os valores de uma função f(x) = x² nos pontos [1, 2, 3, 4, 5] utilizando spline cúbica

In [26]:
from scipy.interpolate import interp1d
import numpy as np

x = np.array([1, 2, 3, 4, 5])

def f(x):
  return x**2

y = f(x)

interpolacao = interp1d(x, y, kind='cubic')

x_novos = np.linspace(1, 5, 100)
y_novos = interpolacao(x_novos)

print(f"Valores interpolados: {y_novos}")


Valores interpolados: [ 1.          1.08244057  1.16814611  1.25711662  1.34935211  1.44485257
  1.543618    1.6456484   1.75094378  1.85950413  1.97132946  2.08641975
  2.20477502  2.32639527  2.45128048  2.57943067  2.71084583  2.84552597
  2.98347107  3.12468115  3.26915621  3.41689624  3.56790123  3.72217121
  3.87970615  4.04050607  4.20457096  4.37190083  4.54249566  4.71635547
  4.89348026  5.07387001  5.25752474  5.44444444  5.63462912  5.82807877
  6.02479339  6.22477298  6.42801755  6.63452709  6.8443016   7.05734109
  7.27364555  7.49321498  7.71604938  7.94214876  8.17151311  8.40414243
  8.64003673  8.879196    9.12162024  9.36730946  9.61626365  9.86848281
 10.12396694 10.38271605 10.64473013 10.91000918 11.17855321 11.45036221
 11.72543618 12.00377512 12.28537904 12.57024793 12.8583818  13.14978063
 13.44444444 13.74237323 14.04356698 14.34802571 14.65574941 14.96673809
 15.28099174 15.59851036 15.91929395 16.24334252 16.57065606 16.90123457
 17.23507805 17.57218651 17.9

## 19. Realize a transformada de Fourier de um sinal discreto composto de senos e cossenos.