<a href="https://colab.research.google.com/github/DaviFerreira0106/notebooks-inteligenciaArtificial/blob/main/Exercicio_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Exercícios NumPy**

## 1. Crie um array unidimensional de 50 elementos contendo números inteiros aleatórios entre 10 e 100.

In [7]:
import numpy as np

array = np.linspace(start=10, stop=100, num=50, dtype=int)
print("\n\n Matriz com números inteiros de 10 à 100: ")
print(array)



 Matriz com números inteiros de 10 à 100: 
[ 10  11  13  15  17  19  21  22  24  26  28  30  32  33  35  37  39  41
  43  44  46  48  50  52  54  55  57  59  61  63  65  66  68  70  72  74
  76  77  79  81  83  85  87  88  90  92  94  96  98 100]


## 2. Gere uma matriz 4x4 com números inteiros de 1 a 16 e extraia a última linha.

In [3]:
array_matriz = np.random.randint(17, size=(4,4))
fatiamento = array_matriz[0:3,:]
print("\n Matriz 4x4 com números inteiros de 1 à 16: ")
print(array_matriz)
print(f"\n Matriz 4x4 com números inteiros de 1 à 16 sem ultima linha: ")
print(fatiamento)


 Matriz 4x4 com números inteiros de 1 à 16: 
[[ 8 14 13 11]
 [ 0  7  3  7]
 [13 15 11 16]
 [14  0 12  4]]

 Matriz 4x4 com números inteiros de 1 à 16 sem ultima linha: 
[[ 8 14 13 11]
 [ 0  7  3  7]
 [13 15 11 16]]


## 3. Crie um array de zeros com comprimento 15 e substitua os valores da 5ª à 10ª posição por 1.

In [5]:
array_zeros = np.zeros(15)
array_zeros[4:10] = 1
print("\n Array de 15 elemnetos que entre o 5º e 10º o valor é 1: ")
print(array_zeros)


 Array de 15 elemnetos que entre o 5º e 10º o valor é 1: 
[0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]


## 4. Gere um array de 100 números inteiros aleatórios e encontre a mediana e a moda dos valores

In [6]:
array_aleatorio = np.random.randint(100, size=101)
mediana = np.median(array_aleatorio)
moda = np.bincount(array_aleatorio).argmax()
print("\n Array de 100 números aleatórios")
print(array_aleatorio)
print(f"\n Mediana do array: {mediana}")
print(f"\n Moda do array: {moda}")


 Array de 100 números aleatórios
[ 4  2 72 24 51 47 84 15 68  6 43 56 65 70 90 80 83 81 63 79 60 60 74 14
 99 90 31 59 67 95 87 24 34  5 43 74  1  5 59 11 17 62  1 63 81 52 57 19
 53 49 12 47 90 12 73 10 58 35 13 10 85 60 81 20 62 39 57 48 49 76 58 24
 58 54 78 40 96 49 57  5 70 16 72 11 76 32 91 74 29 72 87 63 55 26 16 74
 33 81 39 38 67]

 Mediana do array: 57.0

 Moda do array: 74


## 5. Crie um array de 20 elementos contendo números entre 1 e 100 e substitua todos os valores múltiplos de 3 por -3

In [10]:
array = np.linspace(start=1, stop=100, num=20)
array[array % 3 == 0] = -3
print("\n Array de 20 elementos contendo números entre 1 e 100: ")
print(array)


 Array de 20 elementos contendo números entre 1 e 100: 
[  1.           6.21052632  11.42105263  16.63157895  21.84210526
  27.05263158  32.26315789  37.47368421  42.68421053  47.89473684
  53.10526316  58.31578947  63.52631579  68.73684211  73.94736842
  79.15789474  84.36842105  89.57894737  94.78947368 100.        ]
