<a href="https://colab.research.google.com/github/DaviFerreira0106/notebooks-inteligenciaArtificial/blob/main/Exercicio_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Exercícios NumPy**

## 1. Crie um array unidimensional de 50 elementos contendo números inteiros aleatórios entre 10 e 100.

In [ ]:
import numpy as np

array = np.linspace(start=10, stop=100, num=50, dtype=int)
print("\n\n Matriz com números inteiros de 10 à 100: ")
print(array)



 Matriz com números inteiros de 10 à 100: 
[ 10  11  13  15  17  19  21  22  24  26  28  30  32  33  35  37  39  41
  43  44  46  48  50  52  54  55  57  59  61  63  65  66  68  70  72  74
  76  77  79  81  83  85  87  88  90  92  94  96  98 100]


## 2. Gere uma matriz 4x4 com números inteiros de 1 a 16 e extraia a última linha.

In [ ]:
array_matriz = np.random.randint(17, size=(4,4))
fatiamento = array_matriz[0:3,:]
print("\n Matriz 4x4 com números inteiros de 1 à 16: ")
print(array_matriz)
print(f"\n Matriz 4x4 com números inteiros de 1 à 16 sem ultima linha: ")
print(fatiamento)


 Matriz 4x4 com números inteiros de 1 à 16: 
[[ 8 14 13 11]
 [ 0  7  3  7]
 [13 15 11 16]
 [14  0 12  4]]

 Matriz 4x4 com números inteiros de 1 à 16 sem ultima linha: 
[[ 8 14 13 11]
 [ 0  7  3  7]
 [13 15 11 16]]


## 3. Crie um array de zeros com comprimento 15 e substitua os valores da 5ª à 10ª posição por 1.

In [ ]:
array_zeros = np.zeros(15)
array_zeros[4:10] = 1
print("\n Array de 15 elemnetos que entre o 5º e 10º o valor é 1: ")
print(array_zeros)


 Array de 15 elemnetos que entre o 5º e 10º o valor é 1: 
[0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]


## 4. Gere um array de 100 números inteiros aleatórios e encontre a mediana e a moda dos valores

In [ ]:
array_aleatorio = np.random.randint(100, size=101)
mediana = np.median(array_aleatorio)
moda = np.bincount(array_aleatorio).argmax()
print("\n Array de 100 números aleatórios")
print(array_aleatorio)
print(f"\n Mediana do array: {mediana}")
print(f"\n Moda do array: {moda}")


 Array de 100 números aleatórios
[ 4  2 72 24 51 47 84 15 68  6 43 56 65 70 90 80 83 81 63 79 60 60 74 14
 99 90 31 59 67 95 87 24 34  5 43 74  1  5 59 11 17 62  1 63 81 52 57 19
 53 49 12 47 90 12 73 10 58 35 13 10 85 60 81 20 62 39 57 48 49 76 58 24
 58 54 78 40 96 49 57  5 70 16 72 11 76 32 91 74 29 72 87 63 55 26 16 74
 33 81 39 38 67]

 Mediana do array: 57.0

 Moda do array: 74


## 5. Crie um array de 20 elementos contendo números entre 1 e 100 e substitua todos os valores múltiplos de 3 por -3

In [ ]:
array = np.linspace(start=1, stop=100, num=20)
array[array % 3 == 0] = -3
print("\n Array de 20 elementos contendo números entre 1 e 100: ")
print(array)


 Array de 20 elementos contendo números entre 1 e 100: 
[  1.           6.21052632  11.42105263  16.63157895  21.84210526
  27.05263158  32.26315789  37.47368421  42.68421053  47.89473684
  53.10526316  58.31578947  63.52631579  68.73684211  73.94736842
  79.15789474  84.36842105  89.57894737  94.78947368 100.        ]


## 6. Gere uma matriz 5x5 de números aleatórios entre 0 e 1 e encontre a soma de cada coluna

In [1]:
import numpy as np

matriz = np.random.rand(5,5)
soma_coluna = np.sum(matriz, axis=0)

print("\n Matriz 5x5 de números aleatórios entre 0 e 1: ")
print(matriz)
print("\n Soma de cada coluna: ")
print(soma_coluna)


 Matriz 5x5 de números aleatórios entre 0 e 1: 
[[0.71471141 0.47950622 0.11761433 0.70933193 0.31130153]
 [0.66554539 0.98270055 0.0256256  0.89394831 0.99541562]
 [0.61267843 0.11841125 0.50875032 0.33673648 0.71529057]
 [0.37249454 0.69744821 0.65772852 0.41347654 0.80238697]
 [0.0231699  0.04222934 0.86705248 0.94388408 0.29407256]]

 Soma de cada coluna: 
[2.38859966 2.32029556 2.17677125 3.29737734 3.11846723]


## 7. Crie dois arrays de números aleatórios e encontre a correlação entre eles

In [5]:
vetor_1 = np.random.rand(10)
vetor_2 = np.random.rand(10)

print("\n Vetor 1: ")
print(vetor_1)
print("\n Vetor 2: ")
print(vetor_2)

correlacao = np.corrcoef(vetor_1, vetor_2)

print("\n Correlação entre os dois vetores: ")
print(correlacao)


 Vetor 1: 
[0.68500041 0.41930707 0.41276022 0.20354003 0.81598018 0.35492167
 0.04890706 0.79597587 0.95154974 0.83972425]

 Vetor 2: 
[0.87774853 0.47848445 0.33937515 0.67988115 0.13531381 0.67301002
 0.22944674 0.88445607 0.4210279  0.00801171]

 Correlação entre os dois vetores: 
[[ 1.         -0.07273372]
 [-0.07273372  1.        ]]


## 8. Gere uma matriz 3x3 com números inteiros aleatórios e eleve todos os seus elementos ao quadrado

In [7]:
matriz = np.random.randint(10,size=(3,3))
matriz_quadrada = np.power(matriz, 2)

print("\n Matriz 3x3 com números inteiros aleatórios: ")
print(matriz)
print("\n Matriz 3x3 com números ao quadrado: ")
print(matriz_quadrada)


 Matriz 3x3 com números inteiros aleatórios: 
[[3 8 4]
 [0 5 0]
 [4 2 1]]

 Matriz 3x3 com números ao quadrado: 
[[ 9 64 16]
 [ 0 25  0]
 [16  4  1]]


## 9. Crie um array com 10 números aleatórios e normalize seus valores entre 0 e 1

In [8]:
array = np.random.rand(10)
array_normalizado = (array - np.min(array)) / (np.max(array) - np.min(array))

print("\n Array com 10 números aleatórios: ")
print(array)
print("\n Array normalizado entre 0 e 1: ")
print(array_normalizado)


 Array com 10 números aleatórios: 
[0.23726503 0.94149815 0.47274771 0.41467299 0.15609146 0.93553033
 0.64847534 0.76139686 0.59455187 0.99550915]

 Array normalizado entre 0 e 1: 
[0.09670224 0.93565658 0.37723323 0.3080487  0.         0.92854711
 0.58657791 0.72110155 0.52233878 1.        ]


## 10. Crie uma matriz identidade 6x6 e substitua a diagonal principal por valores crescentes de 1 a 6

In [16]:
matriz = np.eye(6)
matriz[np.diag_indices_from(matriz)] = np.arange(1,7)

print("\n Matriz identidade 6x6: ")
print(matriz)


 Matriz identidade 6x6: 
[[1. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0.]
 [0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 6.]]


## 11. Gere um array de 100 números inteiros e encontre o valor que mais se repete no array

In [2]:
import numpy as np

array = np.random.randint(100, size=100)
valor_repetido = np.bincount(array).argmax()

print("\n Array de 100 números inteiros: ")
print(array)
print(f"\n Valor que mais se repete no array: {valor_repetido}")


 Array de 100 números inteiros: 
[14 81  0 58 75 86 72 58 81 50 98 73 73 70 89 99  6 31 25 90 21  3 92 48
 81 50 28 10 28 91 84 35 14 85 23 11 73 63 96 34 13 88 94 65 50 68 11 26
 86 54  1  8 40 89 66 40  5 37 12 80 96 98 17 47 41 21 57 31 72 30 96 41
 34 53 24 14  8 20 40 93 68 41 66 27 54 13 41 22 40  6 33 73 12  9 95 79
 26 84 89  8]

 Valor que mais se repete no array: 40


## 12. Crie uma matriz 4x4 e substitua os valores da diagonal principal por 7

In [3]:
matriz = np.random.randint(10, size=(4, 4))
matriz[np.diag_indices_from(matriz)] = 7

print("\n Matriz 4x4: ")
print(matriz)


 Matriz 4x4: 
[[7 7 3 6]
 [4 7 1 4]
 [2 3 7 4]
 [1 1 5 7]]


## 13. Crie um array contendo os 10 primeiros números pares calcule sua soma cumulativa

In [10]:
import numpy as np

array = np.linspace(start=2, stop=20, num=10, dtype=int)
soma_cumulativa = np.sum(array)

print("\n Array com os 10 primeiros números pares: ")
print(array)
print(f"\n Soma cumulativa do array: {soma_cumulativa}")


 Array com os 10 primeiros números pares: 
[ 2  4  6  8 10 12 14 16 18 20]

 Soma cumulativa do array: 110


## 14. Calcule a diferença entre dois arrays de números aleatórios de mesmo comprimento e encontre a média das diferenças

In [11]:
array_1 = np.random.rand(10)
array_2 = np.random.rand(10)

desvio = np.std(array_1 - array_2)
media_desvio = np.mean(desvio)

print("\n Array 1: ")
print(array_1)
print("\n Array 2: ")
print(array_2)
print(f"\n Desvio entre os dois arrays: {desvio}")
print(f"\n Média dos desvios: {media_desvio}")


 Array 1: 
[0.35168274 0.3923524  0.60649086 0.81552758 0.28249646 0.95303732
 0.83490898 0.71086663 0.05293536 0.54269706]

 Array 2: 
[0.54376376 0.14731845 0.91302614 0.36241669 0.27613191 0.23415017
 0.92790645 0.8305165  0.3463833  0.28498433]

 Desvio entre os dois arrays: 0.322922609788854

 Média dos desvios: 0.322922609788854


## 15. Gere um array contendo 20 números e substitua todos valores maiores que 50 por 50

In [12]:
array = np.random.randint(100, size=20)
array[array > 50] = 50

print("\n Array com 20 números: ")
print(array)


 Array com 20 números: 
[14 49 44 50 50 45 50  9 50 31 43 50  7 46  4 50  0 50 13 43]


## 16. Crie um array unidimensional e reorganize seus valores em uma matriz 3x4

In [13]:
array = np.random.randint(100, size=12)
matriz = np.reshape(array, (3, 4))

print("\n Array unidimensional: ")
print(array)
print("\n Matriz 3x4: ")
print(matriz)


 Array unidimensional: 
[26 50 74 72 43 37 66 98 98 49  3 23]

 Matriz 3x4: 
[[26 50 74 72]
 [43 37 66 98]
 [98 49  3 23]]


## 17. Gere uma matriz 4x4 de números inteiros aleatórios e multiplique cada valor por sua posição na matriz

In [16]:
matriz = np.random.randint(10, size=(4, 4))
matriz_multiplicada = np.multiply(matriz, np.arange(1, 17).reshape(4, 4))

print("\n Matriz 4x4 de números inteiros aleatórios: ")
print(matriz)
print("\n Matriz 4x4 com os valores multiplicados: ")
print(matriz_multiplicada)



 Matriz 4x4 de números inteiros aleatórios: 
[[3 9 3 7]
 [5 3 8 2]
 [1 3 3 9]
 [2 7 9 3]]

 Matriz 4x4 com os valores multiplicados: 
[[  3  18   9  28]
 [ 25  18  56  16]
 [  9  30  33 108]
 [ 26  98 135  48]]


## 18. Crie um array de 10 elementos contendo números entre 1 e 100 e substitua todos os valores multiplos de 5 por 0

In [17]:
array = np.random.randint(100, size=10)
array[array % 5 == 0] = 0

print("\n Array de 10 elementos contendo números entre 1 e 100: ")
print(array)



 Array de 10 elementos contendo números entre 1 e 100: 
[42 18  0 69 26 91 77 12  0  0]


## 19. Crie dois arrays de números inteiros aleatórios de tamanho 20 e calcule o ângulo entre eles (produto escalar normalizado)

In [19]:
arra_1 = np.random.randint(100, size=20)
array_2 = np.random.randint(100, size=20)

produto_escalar = np.dot(arra_1, array_2)
norma_1 = np.linalg.norm(arra_1)
norma_2 = np.linalg.norm(array_2)

print("\n Array 1: ")
print(arra_1)
print("\n Array 2: ")
print(array_2)
print(f"\n Produto escalar entre os dois arrays: {produto_escalar}")
print(f"\n Produto escalar normalizado do array 1: {norma_1}")
print(f"\n Produto escalar normalizado do array 2: {norma_2}")


 Array 1: 
[57  0 80 73 86  3 68 68 25 25  6 61 43 27 16 55  3 68  5 42]

 Array 2: 
[87 10 39 69 25 51 85 71 91 38 38 59 12 25 98 52 61 74  0 56]

 Produto escalar entre os dois arrays: 46265

 Produto escalar normalizado do array 1: 221.17640018772346

 Produto escalar normalizado do array 2: 263.6342162921953


## 20. Crie uma matriz de números inteiros e ncontre o valor mínimo de cada linha

In [21]:
matriz = np.random.randint(20, size=(4,4))
minimo = np.min(matriz, axis=1)

print("\n Matriz de números inteiros: ")
print(matriz)
print("\n Valor mínimo de cada linha: ")
print(minimo)


 Matriz de números inteiros: 
[[ 9  0 16 19]
 [ 4  7 14 18]
 [18 18  7  1]
 [16  1 16 18]]

 Valor mínimo de cada linha: 
[0 4 1 1]
